theme: jekyll-theme-minimal
name: Torpedo Chauchistico
description: Crypto-Glosario desarrollado por el Proyecto Chaucha, basado en la información de [bitcoin.org](https://bitcoin.org/), [Bitcoin Wiki](https://en.bitcoin.it/wiki/) y el trabajo de la comunidad.
